### ISSUE TITLE
How do I query for a month?

### ISSUE THREAD

**Issue by martinsookael** [shiki/kaiseki#25]
I'm trying to query posts from one specific month. 
Current not working version:

  var params = {
    where: {
      userId: userId,
      dated: {
        $gte: startDate,
        $lte: endDate
      }
    },
    order: 'dated'
  }
  kaiseki.getObjects('Posts', params, function(err, response, body, success) {
         // ....
  });

How do I achieve this in kaiseki?

**Comment by shiki** [comment]
@martinsookael Try doing it like this:

    var params = {
      where: {
        'dated': {
          '$gte': { '__type': 'Date', 'iso': '2011-08-21T18:02:52.249Z'}
        }
      }
    }

You can read more about Data Types here: https://parse.com/docs/rest#objects-types

**Comment by martinsookael** [comment]
Thank you so much!
