### ISSUE TITLE
Parse only supports batches of up to 50 requests

### ISSUE THREAD

**Issue by searls** [shiki/kaiseki#26]
Just reading the Parse API guide, it mentions:

> To reduce the amount of time spent on network round trips, you can create, update, or delete up to 50 objects in one call, using the batch endpoint.

But reading kaiseki's source just now, it doesn't seem to do anything to handle or break up the batches in `createObjects` or `updateObjects` into groups of 50. Is this something you've run into or considered, @shiki?

Thanks!

**Comment by shiki** [comment]
@searls Not really. Does the API return an error if you try to send more than 50?

**Comment by searls** [comment]
We haven't tried yet. We intend to run some load tests soon and that should tell us.
