### ISSUE TITLE
How is kaiseki different from the Parse Javascript SDK run on Node.js?

### ISSUE THREAD

**Issue by fatuhoku** [shiki/kaiseki#29]
I just read http://blog.parse.com/2012/10/11/the-javascript-sdk-in-node-js/ and am wondering what Kaiseki's purpose is... if any!

**Comment by shiki** [comment]
@fatuhoku This library existed before that. It served my purpose during that time. :)

**Comment by fatuhoku** [comment]
Thanks good to know!
