### ISSUE TITLE
Can you switch to request-promise ?

### ISSUE THREAD

**Issue by sunshineo** [shiki/kaiseki#30]
First, thank you for this library. I switched from build headers, call each request myself and parse response to couple line of code.
However, I'm in callback hell now. Explicit naming all my callback function did solve the pyramid problem but a hell is still a hell when it is flat.
Can you switch to https://www.npmjs.com/package/request-promise I wonder? And return the promise to us so I can make my code readable.

Thank you very much!

**Comment by shiki** [comment]
@sunshineo Is it easy to switch to that? Can we probably make it an option?

**Comment by shiki** [comment]
I'm up for this, I just don't have time right now. And I'm not sure if I want to break compatibilities.

**Comment by sunshineo** [comment]
@shiki They say it is a drop in replacement. I may not break anything.

**Comment by shiki** [comment]
@sunshineo Feel free to send a pull request if you want to.

**Comment by sunshineo** [comment]
I'll send out a pull request soon.

**Comment by nthhtn** [comment]
I tried promisifyAll(kaiseki) and it worked perfectly

**Comment by sunshineo** [comment]
Oh, I totally forgot about this. @nthhtn can you create a pull request?

**Comment by markmssd** [comment]
How's this going @nthhtn ? If you need I can probably help, I think it would make this library even more awesome than it already is. Let me know!

**Comment by nthhtn** [comment]
To be honest, I didn't do anything much, I just used Bluebird and this
command :D

const Promise=require('bluebird');

module.exports=function(kaiseki){
return Promise.promisifyAll(kaiseki);
})

2016-09-17 5:58 GMT+07:00 Mark Massoud <notifications@github.com>:

**Comment by sunshineo** [comment]
@nthhtn Looks cool. I start to self host parse and I don't need to use this repo any more.
